### ISSUE TITLE
How to load models  in config.yml?

### ISSUE THREAD

**Issue by web-girlfriend** [liangyuxin42/dreamcatcher#1]
How to load models  in config.yml, such as General_RM, bge-large-zh-v1.5, and model path?

That would be helpful!

**Comment by liangyuxin42** [comment]
For bge-large-zh-v1.5, you can download it (https://huggingface.co/BAAI/bge-large-zh-v1.5) to your own path and put the model path (your/path/to//bge-large-zh-v1.5) to the config.yml. You can also put  “BAAI/bge-large-zh-v1.5” in embedding_model_path, and huggingface transformers will download it for you.
As for General_RM, you can choose any available reward model. For example: https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-7B-Reward. Some reward model might require some changes in the inference code of reward model in reward_model_scorer.py.

Hope this helps!~
